[workspace]
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
authors = ["Joshua Wong"]
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
anyhow = "1.0.65"
clap = { version = "4.0.15", features = ["derive", "wrap_help"] }
fixedbitset = "0.4.2"
itertools = "0.10.5"
miette = { version = "5.3.0", features = ["fancy"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
serde_yaml = "0.9.13"
pretty_assertions = "1.3.0"
indexmap = { version = "1.9.1", features = ["std"] }
once_cell = "1.15.0"
regex = "1.6.0"
rustc-hash = "1.1.0"
smallvec = { version = "1.10.0", features = ["union", "may_dangle"] }
swc_core = { version = "0.38.17", features = ["common_perf", "common", "common_sourcemap", "ecma_visit_path", "ecma_utils", "ecma_ast", "swc", "ecma_visit", "ecma_transforms", "ecma_transforms_module", "ecma_transforms_typescript", "ecma_parser_typescript"] }
thiserror = "1.0.37"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tracing-tree = "0.2.1"
typed-arena = "2.0.1"
typed-index-collections = "3.1.0"
walkdir = "2.3.2"
forge_loader = { path = "crates/forge_loader" }
forge_analyzer = { path = "crates/forge_analyzer" }
forge_utils = { path = "crates/forge_utils" }

[profile.release]
debug = true
