[workspace]
members = ["crates/*"]

[workspace.package]
authors = ["Joshua Wong"]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.65"
clap = { version = "3.2.21", features = ["derive", "wrap_help"] }
itertools = "0.10.4"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
serde_yaml = "0.9.11"
pretty_assertions = "1.3.0"
indexmap = { version = "1.9.1", features = ["std"] }
once_cell = "1.14.0"
regex = "1.6.0"
rustc-hash = "1.1.0"
smallvec = { version = "1.9.0", features = ["union", "may_dangle"] }
swc_core = { version = "0.23.20", features = ["common_perf", "common", "__ecma", "swc_atoms", "swc_ecma_ast", "swc_ecma_loader", "swc_ecma_visit", "swc_ecma_utils", "ecma_ast", "swc", "ecma_visit", "ecma_transforms", "ecma_transforms_module", "ecma_transforms_typescript"] }
swc_ecma_parser = "0.119.9"
tracing = "0.1.36"
walkdir = "2.3.2"
