name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: build (alpine)
        uses: addnab/docker-run-action@v3
        with:
          image: rust:alpine
          options: -v ${{ github.workspace }}:/workspace
          run: |
            apk update
            apk add --no-cache musl-dev
            cd /workspace
            cargo build --release
            mv target/release/fsrt fsrt-alpine
      # - name: Release
      #   uses: softprops/action-gh-release@v2.2.2
      #   with:
      #     files: fsrt-alpine
